import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";   // Global Bootstrap styles
import "@/components/App.css";                   // Your custom global CSS
import SessionWrapper from "./SessionWrapper";   // ← Added this

// Load Google fonts using Next.js built-in font optimization.
// These fonts automatically generate CSS variables (--font-geist-sans, etc.)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata controls the <head> tag for the entire site.
// This applies to every page unless overridden.
export const metadata: Metadata = {
  title: "Music App",
  description: "Generated by Leo Godinez",
  icons: {
    icon: "/favicon.ico",
  }
};

// The RootLayout wraps EVERY page in the app.
// It defines the global HTML structure and shared styling.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Apply the loaded Google font variables + antialiasing to the entire site.
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap whole app with SessionProvider so NextAuth works */}
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
